#!/usr/bin/env python

import rospy
import tf2_ros
import geometry_msgs.msg

t = geometry_msgs.msg.TransformStamped()

t.header.frame_id = "map"
t.child_frame_id = "cf1/odom"

t.transform.translation.x = 0
t.transform.translation.y = 0
t.transform.translation.z = 0
t.transform.rotation.w = 1

    # Publish these transforms statically forever
rospy.init_node('Map2odom')

def main():
    broadcaster = tf2_ros.StaticTransformBroadcaster()
    broadcaster.sendTransform(t)
    rospy.spin()

if __name__ == "__main__":
   main()

