#!/usr/bin/env python

from geometry_msgs.msg import PoseStamped, PoseWithCovarianceStamped
from nav_msgs.msg import OccupancyGrid, Path
import json
import math
import numpy

# Load world JSON
with open('/home/maverick/dd2419_ws/src/course_packages/dd2419_resources/worlds_json/awesome.world.json') as f:
	world = json.load(f)


# Initialize occupancy grid message
map_msg = OccupancyGrid()
map_msg.header.frame_id = 'map'
resolution = 0.01
width = 500
height = 500

# Map update rate (defaulted to 5 Hz)
rate = 5.0

