#!/usr/bin/env python

import math
import rospy
import tf2_geometry_msgs
from geometry_msgs.msg import PoseStamped
import simple_localization


rospy.init_node('Move_drone')
pub_cmd  = rospy.Publisher('move_base_simple/goal', PoseStamped, queue_size=2)

cmd = PoseStamped()
cmd.header.stamp = rospy.Time.now()
cmd.header.frame_id = "cf1/odom"

if pub_cmd.get_num_connections() <= 0:
	rospy.sleep(2.5)

cmd.pose.position.x = 0
cmd.pose.position.y = -1
cmd.pose.position.z = 0.3
cmd.pose.orientation.w = 1

pub_cmd.publish(cmd)
rospy.sleep(3.5)

cmd.pose.position.x = 1.5
cmd.pose.position.y = -1
cmd.pose.orientation.z = 0.924 #135 CCW wrt origin
cmd.pose.orientation.w = 0.383

pub_cmd.publish(cmd)
rospy.sleep(4.5)

cmd.pose.position.x = 0.5
cmd.pose.position.y = 0

pub_cmd.publish(cmd)
rospy.sleep(4.5)

cmd.pose.position.x = 0
cmd.pose.position.y = 1

pub_cmd.publish(cmd)
rospy.sleep(2.5)

cmd.pose.orientation.z = 1 #180 CCW wrt origin
cmd.pose.orientation.w = 0

pub_cmd.publish(cmd)
rospy.sleep(2.5)

cmd.pose.position.x = -1
cmd.pose.position.y = 1

pub_cmd.publish(cmd)
rospy.sleep(2.5)

cmd.pose.position.x = -1.75
cmd.pose.position.y = 1

pub_cmd.publish(cmd)
rospy.sleep(2.5)
'''
cmd.pose.orientation.z = 0.707 #270 CCW
cmd.pose.orientation.w = -0.707

pub_cmd.publish(cmd)
rospy.sleep(2.5)

cmd.pose.position.x = -1.75
cmd.pose.position.y = 0.5
cmd.pose.orientation.z = 0 #0
cmd.pose.orientation.w = 1

pub_cmd.publish(cmd)
rospy.sleep(2.5)

cmd.pose.position.x = -0.8
cmd.pose.position.y = 0.5

pub_cmd.publish(cmd)
rospy.sleep(2.5)

cmd.pose.orientation.z = 0.707 #270 CCW
cmd.pose.orientation.w = -0.707

pub_cmd.publish(cmd)
rospy.sleep(2.5)

cmd.pose.position.x = -0.8
cmd.pose.position.y = 0

pub_cmd.publish(cmd)
rospy.sleep(2.5)

cmd.pose.orientation.z = 1 #180 CCW wrt origin
cmd.pose.orientation.w = 0

pub_cmd.publish(cmd)
rospy.sleep(2.5)

cmd.pose.position.x = -1.5
cmd.pose.position.y = 0

pub_cmd.publish(cmd)
rospy.sleep(2.5)

cmd.pose.position.x = -2.5
cmd.pose.position.y = 0

pub_cmd.publish(cmd)
rospy.sleep(2.5)

cmd.pose.orientation.z = 0.707 #90 CCW
cmd.pose.orientation.w = 0.707

pub_cmd.publish(cmd)
rospy.sleep(2.5)
'''
cmd.pose.position.z = 0.6

pub_cmd.publish(cmd)
rospy.sleep(2.5)

cmd.pose.position.x = -2.5
cmd.pose.position.y = 0.5

pub_cmd.publish(cmd)
rospy.sleep(2.5)

cmd.pose.position.z = 0.3

pub_cmd.publish(cmd)
rospy.sleep(2.5)

cmd.pose.position.x = -3.25
cmd.pose.position.y = 0.5

pub_cmd.publish(cmd)
rospy.sleep(2.5)

cmd.pose.position.x = -2.5
cmd.pose.position.y = 0.5

pub_cmd.publish(cmd)
rospy.sleep(2.5)

cmd.pose.orientation.z = 0.707 #270 CCW
cmd.pose.orientation.w = -0.707

pub_cmd.publish(cmd)
rospy.sleep(2.5)

cmd.pose.position.x = -2.5
cmd.pose.position.y = 0

pub_cmd.publish(cmd)
rospy.sleep(2.5)

cmd.pose.position.x = -2.5
cmd.pose.position.y = -1

pub_cmd.publish(cmd)
rospy.sleep(2.5)

cmd.pose.orientation.z = 0 #0
cmd.pose.orientation.w = 1

pub_cmd.publish(cmd)
rospy.sleep(2.5)

pub_cmd.publish(cmd)
rospy.sleep(2.5)

cmd.pose.position.x = -2
cmd.pose.position.y = -1

pub_cmd.publish(cmd)
rospy.sleep(2.5)

cmd.pose.position.x = -1
cmd.pose.position.y = -0.5

pub_cmd.publish(cmd)
rospy.sleep(2.5)


cmd.pose.position.x = -0.25
cmd.pose.position.y = -0.75

cmd.pose.orientation.z = 0.383 #45 CCW wrt origin
cmd.pose.orientation.w = 0.924

pub_cmd.publish(cmd)
rospy.sleep(2.5)

cmd.pose.position.x = 0.5
cmd.pose.position.y = 0

pub_cmd.publish(cmd)
rospy.sleep(2.5)

cmd.pose.position.x = 1.5
cmd.pose.position.y = 1

pub_cmd.publish(cmd)
rospy.sleep(2.5)


def main():
    rate = rospy.Rate(100)  # Hz
  #  while not rospy.is_shutdown():
  #      if cmd:
     #       publish_cmd(cmd)
     #   rate.sleep()

if __name__ == '__main__':
    main()
