#!/usr/bin/env python

import numpy as np
import pylab as pl
from matplotlib import collections  as mc

airspace = [[(-4, -2), (-4, 2)], [(-4, 2), (2, 2)], [(-4, -2), (2, -2)], [(2, -2), (2, 2)]]
walls = [[(-2, 2), (-2, 0.25)], [(-2, 0.25), (-1, 0.25)]]
gates = [[(1.07322, -0.676777), (1.42678, -0.323223)], [(0.073223, 0.323223), (0.426777, 0.676777)],
 [(-1.5, 0.75), (-1.5, 0.80)], [(-1.5, 1.20), (-1.5, 1.25)], [(-3, 0.25), (-3, 0.30)], [(-3, 0.70), (-3, 0.75)],
 [(-2.25, -0.75), (-2.30, -0.75)], [(-2.70, -0.75), (-2.75, -0.75)], [(-1.5, -0.5), (-1.5, -0.55)], [(-1.5, -0.95), (-1.5, -1)], 
[(0.073223, -0.323223), (0.426777, -0.676777)], [(1.073220, 0.676777), (1.426780, 0.323223)]]

lines = airspace + walls + gates

lc = mc.LineCollection(lines, linewidths=3)
fig, ax = pl.subplots()
ax.add_collection(lc)
ax.autoscale()
ax.margins(0.1)

#pl.show()

pl.savefig('nav_map2.png', bbox_inches='tight')
