#!/usr/bin/env python

import math
import rospy
from nav_msgs.msg import Odometry, OccupancyGrid
from geometry_msgs.msg import PoseStamped, Pose, Twist
from gazebo_msgs.srv import GetModelState, GetModelStateRequest




rospy.init_node('odom_publish')
odom_pub  = rospy.Publisher('/odom', Odometry, queue_size=2)

rospy.wait_for_service('/gazebo/get_model_state')
get_model_srv = rospy.ServiceProxy('/gazebo/get_model_state',GetModelState)

odom = Odometry()

odom.header.stamp = rospy.Time.now()
odom.header.frame_id = "cf1/odom"
odom.child_frame_id = "cf1/base_link"

model = GetModelStateRequest()
model.model_name = 'cf1'



def main():
    rate = rospy.Rate(10)  # Hz
 
    while not rospy.is_shutdown():
	result = get_model_srv(model)

	odom.pose.pose = result.pose
	odom.twist.twist = result.twist        

	odom_pub.publish(odom)
        rate.sleep()

if __name__ == '__main__':
    main()
